name: dnotes
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # for improve perfomance and better coding
  get: ^4.6.5
  # for using svg image
  flutter_svg: ^1.1.6
  # for animation
  simple_animations: ^5.0.0+3
  # for showing toast message
  fluttertoast: ^8.2.1
  # for checking diffrent device preview
  device_preview: ^1.1.0
  # for launching link and url
  url_launcher: ^6.1.10
  # for storing data
  get_storage: ^2.1.1
  # for formating date
  intl: ^0.17.0
  # for formating code
  code_text_field: ^1.1.0
  # for highlighting text
  highlight: ^0.7.0
  # for highlighting text
  flutter_highlight: ^0.7.0
  # for sharing text and image
  share_plus: ^6.3.0
  # for using firebase services
  firebase_core: ^2.14.0
  # for save data in firebase firestore
  cloud_firestore: ^4.7.1
  # for showing data in Grid View
  flutter_staggered_grid_view: ^0.6.2
  # for using animation from json
  lottie: ^2.3.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/

  fonts:
    - family: SourceCodePro
      fonts:
        - asset: assets/fonts/SourceCodePro-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/SourceCodePro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/SourceCodePro-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/SourceCodePro-Italic.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/SourceCodePro-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/SourceCodePro-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/SourceCodePro-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/SourceCodePro-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/SourceCodePro-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/SourceCodePro-BoldItalic.ttf
          weight: 700
          style: italic


    - family: AnekGujarati
      fonts:
        - asset: assets/fonts/AnekGujarati-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/AnekGujarati-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/AnekGujarati-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/AnekGujarati-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/AnekGujarati-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/AnekGujarati-ExtraBold.ttf
          weight: 800
          style: normal



  # flutter build web --web-renderer=html
  # flutter build apk --obfuscate --split-debug-info=/<project-name>/<directory>
