name: dnotes
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5 # for improve perfomance and better coding
  simple_animations: ^5.0.0+3 # for using animation
  fluttertoast: ^8.2.1  # for showing toast message
  url_launcher: ^6.1.10 # for launching link and url
  get_storage: ^2.1.1 # for storing data
  intl: ^0.17.0 # for formating date
  code_text_field: ^1.1.0 # for formating code
  highlight: ^0.7.0 # for highlighting text
  flutter_highlight: ^0.7.0 # for highlighting text
  share_plus: ^6.3.0 # for sharing text and image
  firebase_core: ^2.14.0 # for using firebase services
  cloud_firestore: ^4.7.1 # for save data in firebase firestore
  flutter_staggered_grid_view: ^0.6.2 # for showing data in Grid View
  lottie: ^2.3.2 # for using animation from json
  flutter_svg: ^2.0.7 # for using svg pictures
  vector_graphics: ^1.1.7 # for rendering svg images
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/

  fonts:
    - family: AnekGujarati
      fonts:
        - asset: assets/fonts/AnekGujarati-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/AnekGujarati-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/AnekGujarati-Medium.ttf
          weight: 500
          style: normal
        - asset: assets/fonts/AnekGujarati-SemiBold.ttf
          weight: 600
          style: normal
        - asset: assets/fonts/AnekGujarati-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/AnekGujarati-ExtraBold.ttf
          weight: 800
          style: normal



  # flutter build web --web-renderer html --release
  # flutter build web --web-renderer canvaskit --release
  # flutter build apk --obfuscate --split-debug-info=/<project-name>/<directory>
