// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAu9xjUg_PdoOJw8Q5oGYArGJud5c9YZW4',
    appId: '1:459885519431:web:3a5d423bf568f96ef74762',
    messagingSenderId: '459885519431',
    projectId: 'notes-c7a4d',
    authDomain: 'notes-c7a4d.firebaseapp.com',
    storageBucket: 'notes-c7a4d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq6W8mPurk8N-t91cg1_cUiOWzQtDWRzk',
    appId: '1:459885519431:android:476f43d720aafcc2f74762',
    messagingSenderId: '459885519431',
    projectId: 'notes-c7a4d',
    storageBucket: 'notes-c7a4d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQC0fYrA8TzEkweGT2TlPHRLEdzVT3tMI',
    appId: '1:459885519431:ios:f217e74f62d1b9d7f74762',
    messagingSenderId: '459885519431',
    projectId: 'notes-c7a4d',
    storageBucket: 'notes-c7a4d.appspot.com',
    iosClientId: '459885519431-qe9jneogrp5trn69t2cm3gc552tnd71k.apps.googleusercontent.com',
    iosBundleId: 'com.dkpro.notes',
  );
}
